"""Revision5

Revision ID: 8785c1ecf946
Revises: 31d1bc2dce71
Create Date: 2023-10-19 00:34:09.669325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8785c1ecf946'
down_revision: Union[str, None] = '31d1bc2dce71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('matched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availabilities', 'matched')
    # ### end Alembic commands ###
