"""revision3

Revision ID: b5843aa46f9f
Revises: 03717db68cec
Create Date: 2023-10-11 15:03:44.018611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5843aa46f9f'
down_revision: Union[str, None] = '03717db68cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_availability', 'availabilities', ['date_hour', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_availability', 'availabilities', type_='unique')
    # ### end Alembic commands ###
